THP_Event_Brite_Lite-master/config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :users
end

THP_Event_Brite_Lite-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

THP_Event_Brite_Lite-master/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :guest, class_name: "User"
  belongs_to :event
  validates :guest_id, uniqueness: { scope: [:event_id] }
  after_create :new_attendee_send

  def new_attendee_send
    AdminMailer.new_attendance(self).deliver_now
  end
end
 

THP_Event_Brite_Lite-master/app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :guests, class_name: "User", through: :attendances
  belongs_to :admin, class_name: "User" 
  validates :start_date, presence: true
  validate :start_must_be_future

  validates :duration, presence: true
  validate :duration_5
  validate :duration_positive

  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, inclusion: { in: 1..1000}
  validates :location, presence: true


  def start_must_be_future
    return unless start_date 
    errors.add(:start_date, "ne doit pas être passée") unless start_date > Time.now
  end

  def duration_5
    return unless duration
    errors.add(:duration, "doit être un multiple de 5") unless (duration % 5) == 0
  end
  
  def duration_positive
    return unless duration
    errors.add(:duration, "doit être supérieur à 0") unless duration > 0
  end
end
 

THP_Event_Brite_Lite-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :guest_attendances, foreign_key: 'guest_id', class_name: "Attendance"
  has_many :admin_events, foreign_key: 'admin_id', class_name: "Event"
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

THP_Event_Brite_Lite-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UsersHelper
end

THP_Event_Brite_Lite-master/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
  end

  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end


end

THP_Event_Brite_Lite-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
  end

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    else
      if @user.update(user_params)
        flash[:success] = "Your profile has been updated."
        redirect_to user_path(@user.id)
      else
        render 'edit'
      end
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end

end

THP_Event_Brite_Lite-master/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

THP_Event_Brite_Lite-master/app/helpers/events_helper.rb
module EventsHelper
end

THP_Event_Brite_Lite-master/app/helpers/users_helper.rb
module UsersHelper

  def current_user?(user)
    user == current_user.id
  end

end

THP_Event_Brite_Lite-master/app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Eventbrite</h1>
    <p>Participate to the best events of your city</p><br />
    <%=link_to "New event", new_event_path, type:"button", class: "btn btn-outline-primary" %>
  </div>
</div>

<div class="container container-event">
 
  <% Event.order("start_date ASC").all.each do |event| %>
    <h3><%= link_to "#{event.title}", event_path(event) %></h3>
    <p>> <%= event.location %></p><br />
    <p><%= event.start_date.strftime("%d/%m/%Y %H:%M") %></p><br/>
  <%end%>
</div>

THP_Event_Brite_Lite-master/app/views/events/show.html.erb
<div class= "container-fluid">
  <h3><%= @event.title %></h3>
  <p>> <%= @event.location %></p><br />
  <p><%= @event.start_date.strftime("%d/%m/%Y %H:%M") %></p><br/>
</div>

THP_Event_Brite_Lite-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBriteLite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-oOs/gFavzADqv3i5nCM+9CzXe3e5vXLXZ5LZ7PplpsWpTCufB7kqkTlC9FtZ5nJo" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>EventBriteLite</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Event Brite Lite</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%=link_to "Home", root_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to "#{current_user.email}", user_path(current_user), class:"nav-link"%>
              <%end%>
            </li>
            <li class="nav-item dropdown">
              <% if user_signed_in? %>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Settings
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <ul>
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                    <%= link_to "Edit email / password", edit_user_registration_path, class: "dropdown-item" %>
                  </ul>
                </div>
              <% else %>
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Login/ Sign up
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <ul>
                      <%=link_to "Login", new_user_session_path, class:"dropdown-item" %>
                      <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item"%>
                    </ul>
                  </div>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

THP_Event_Brite_Lite-master/app/views/users/show.html.erb
<div class="container-fluid text-center">
  <div class="texte-bienvenue">
    <h2>Son blaz : <%= @current_user.first_name %> <%= @current_user.last_name %></h2>

    <p>Contactez cette comère : <%= @current_user.email %></p><br />

  </div>
</div>